lang: en-US
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
remote_theme: mmistakes/minimal-mistakes
title: Master Notions
description: The Mythology of Glenn Greenwald
header:
 image: /assets/images/twitter-cardbr.jpg
twitter: 
  card: "summary_large_image"
  image: https://masternotions.com/assets/images/twitter-card2.jpg
  site: "ggreenwald"
  title: Master Notions
  description: Mythology of GG
google_analytics: G-J73QXGV4YW
minimal_mistakes_skin: "aqua"
sidebar:
 - image: /assets/images/EshEH_WU4AE7WXV.jpg
repository: alansfr/alansfr.github.io
url: masternotions.com
baseurl: ""

