lang: en-US
title: Greenwald's Cockperialism
description: Fearless investigative journalism into Glenn Greenwald's pornography empire.
footer: MADE IN U.S.A.
twitter_site: @wokyleeks
twitter_creator: @squirtleh2o
twitter_card: https://cockperialism.com/assets/images/twitter-card.jpg
google_analytics: UA-176936640-1
